services:
  - type: web
    name: projetosite-art-resumos
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
